name: Python application

on: [push]

env:
  FILE_NAME: my-artifact.txt

jobs:
  print-env:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code 
      uses: actions/checkout@v2

    - name: Create file
      run: echo "this is a sample file" > sample.txt

    - name : save artifact
      uses: actions/upload-artifact@v4
      with :
          path: ./sample.txt

